#!/bin/bash

#SBATCH --partition=gpu_titanrtx_shared_course
#SBATCH --gres=gpu:1
#SBATCH --job-name=bilstm
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=3
#SBATCH --time=10:00:00
#SBATCH --mem=32000M
#SBATCH --output=bilstm_%A.out

module purge
module load 2021
module load Anaconda3/2021.05

cd $HOME/ATCS/

source activate atcs_gpu

srun python -u train.py --encoder_type biLSTMEncoder --outputmodelname bilstm_model.pickle --n_epochs 10